"""
BAC - Export Handlers
Export Use Case Descriptions to various formats
"""
import io
import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models.irm import UseCaseDescription


def export_to_markdown(use_case: "UseCaseDescription") -> str:
    """
    Export use case to Markdown format.

    Args:
        use_case: The use case to export

    Returns:
        Markdown string
    """
    lines = []

    # Title
    lines.append(f"# {use_case.title}")
    lines.append("")

    # Description if present
    if use_case.description:
        lines.append(use_case.description)
        lines.append("")

    # Metadata
    lines.append("---")
    lines.append(f"**Status:** {use_case.meta.status.value}")
    if use_case.template_id:
        lines.append(f"**Template:** {use_case.template_id}")
    lines.append(f"**Created:** {use_case.meta.created_at.isoformat() if use_case.meta.created_at else 'Unknown'}")
    lines.append("---")
    lines.append("")

    # Sections
    for section in sorted(use_case.sections, key=lambda s: s.order):
        lines.append(f"## {section.title}")
        lines.append("")

        if section.content:
            lines.append(section.content)
            lines.append("")

        # BAM References
        if section.bam_references:
            lines.append("### Architecture References")
            lines.append("")
            for ref in section.bam_references:
                ref_link = ref.deep_link or f"#{ref.element_id}"
                lines.append(f"- **{ref.element_type}**: [{ref.element_name}]({ref_link}) ({ref.tool_type})")

                # Embed diagram if available
                if ref.embed_url:
                    lines.append(f"  ![{ref.element_name}]({ref.embed_url})")

            lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by BAC (Business Analysis Copilot)*")

    return "\n".join(lines)


def export_to_irm_jsonld(use_case: "UseCaseDescription") -> dict:
    """
    Export use case to IRM JSON-LD format for SAC handover.

    Args:
        use_case: The use case to export

    Returns:
        IRM JSON-LD dictionary
    """
    return use_case.to_dict()


def export_to_word(use_case: "UseCaseDescription") -> io.BytesIO:
    """
    Export use case to Word document.

    Args:
        use_case: The use case to export

    Returns:
        BytesIO buffer containing Word document
    """
    try:
        from docx import Document
        from docx.shared import Inches, Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("python-docx is required for Word export. Install with: pip install python-docx")

    doc = Document()

    # Title
    title = doc.add_heading(use_case.title, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Description
    if use_case.description:
        doc.add_paragraph(use_case.description)

    # Metadata table
    doc.add_heading("Document Information", level=1)
    table = doc.add_table(rows=3, cols=2)
    table.style = 'Table Grid'

    cells = table.rows[0].cells
    cells[0].text = "Status"
    cells[1].text = use_case.meta.status.value

    cells = table.rows[1].cells
    cells[0].text = "Template"
    cells[1].text = use_case.template_id or "Custom"

    cells = table.rows[2].cells
    cells[0].text = "Created"
    cells[1].text = use_case.meta.created_at.isoformat() if use_case.meta.created_at else "Unknown"

    doc.add_paragraph()

    # Sections
    for section in sorted(use_case.sections, key=lambda s: s.order):
        doc.add_heading(section.title, level=1)

        if section.content:
            # Simple markdown to Word conversion (basic)
            for para in section.content.split("\n\n"):
                para = para.strip()
                if not para:
                    continue

                # Handle headers
                if para.startswith("### "):
                    doc.add_heading(para[4:], level=3)
                elif para.startswith("## "):
                    doc.add_heading(para[3:], level=2)
                elif para.startswith("# "):
                    doc.add_heading(para[2:], level=1)
                elif para.startswith("- "):
                    # Bullet list
                    for line in para.split("\n"):
                        if line.strip().startswith("- "):
                            doc.add_paragraph(line.strip()[2:], style='List Bullet')
                else:
                    doc.add_paragraph(para)

        # BAM References
        if section.bam_references:
            doc.add_heading("Architecture References", level=2)
            for ref in section.bam_references:
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(f"{ref.element_type}: ").bold = True
                p.add_run(f"{ref.element_name} ({ref.tool_type})")

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by BAC (Business Analysis Copilot)")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    return buffer
